#### Model Development and Evaluation

#### Objective

The objective of this notebook is to train and evaluate machine learning models for predicting book popularity using features engineered during the preprocessing stage.

The dataset includes:
- Genre-based features obtained through multi-label encoding
- Text features extracted from book descriptions using TF-IDF
- Publication year
- Page count

The target variable is the Popularity_Score, derived from the logarithm of the rating count.

In [7]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [8]:
# Load PreProcessed Dataset
df = pd.read_csv("preprocessed_books.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_books.csv'

In [ ]:
df.head()

,Page_Count,Popularity_Score,Pub_Year,fiction,fantasy,romance,young adult,historical fiction,nonfiction,mystery,...,wa,want,war,way,woman,work,world,year,york,young
0,2.088682,15.242884,-0.583660,1,1,0,1,0,0,0,...,0.120108,0.0,0.000000,0.141846,0.0,0.0,0.228578,0.0,0.0,0.0
1,0.037712,16.126869,-0.388194,1,1,0,1,0,0,0,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
2,0.022705,15.081943,-1.365522,1,0,0,0,1,0,0,...,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.244259,0.0,0.0,0.0
3,1.128228,14.889819,-0.974591,1,0,0,1,1,0,0,...,0.152579,0.0,0.000000,0.000000,0.0,0.0,0.145186,0.0,0.0,0.0
4,1.528417,15.127649,-0.974591,1,1,0,1,0,0,0,...,0.000000,0.0,0.261174,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0

#### Feature / Target Split

The target variable used for prediction is Popularity_Score. All remaining columns were treated as input features for model training.

In [ ]:
X = df.drop(columns=["Popularity_Score"])

y = df["Popularity_Score"]

In [ ]:
X.columns

Index(['Page_Count', 'Pub_Year', 'fiction', 'fantasy', 'romance',
       'young adult', 'historical fiction', 'nonfiction', 'mystery',
       'paranormal',
       ...
       'wa', 'want', 'war', 'way', 'woman', 'work', 'world', 'year', 'york',
       'young'],
      dtype='str', length=114)

#### Train-Test Split
The dataset was divided into training and testing sets to evaluate model performance on unseen data.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Linear Regression Model

In [ ]:
lr_model = LinearRegression()

lr_model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred_lr = lr_model.predict(X_test)

In [ ]:
lr_results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred_lr
})

lr_results

         Actual  Predicted
1760  10.440887   8.624090
3326   4.304065   4.748024
1770  12.842705  12.061286
3176   9.747360  11.844854
2099  10.234588  10.734631
...         ...        ...
2510  10.529880   8.223329
2752  10.698379  10.319695
1869   4.025352   1.931527
423   12.350658  10.954504
2990   8.481773   7.329323

[800 rows x 2 columns]

In [ ]:
# Evaluate Linear Regression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [ ]:
lr_mae = mean_absolute_error(y_test, y_pred_lr)

lr_rmse = np.sqrt(mean_squared_error(y_test, y_pred_lr))

lr_r2 = r2_score(y_test, y_pred_lr)

print("Linear Regression Performance")
print("MAE:", lr_mae)
print("RMSE:", lr_rmse)
print("R2 Score:", lr_r2)

Linear Regression Performance
MAE: 1.8117190480420218
RMSE: 2.2858539208277255
R2 Score: 0.5066378917375074

Random Forest Regressor

In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
y_pred_rf = rf_model.predict(X_test)

In [ ]:
rf_results = pd.DataFrame({
    "Actual": y_test,
    "Predicted": y_pred_rf
})

rf_results

         Actual  Predicted
1760  10.440887   7.522620
3326   4.304065   3.147272
1770  12.842705  12.462135
3176   9.747360  10.586927
2099  10.234588  10.695670
...         ...        ...
2510  10.529880   7.983594
2752  10.698379   9.315624
1869   4.025352   2.906875
423   12.350658  11.362622
2990   8.481773   9.873766

[800 rows x 2 columns]

In [ ]:
rf_mae = mean_absolute_error(y_test, y_pred_rf)

rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))

rf_r2 = r2_score(y_test, y_pred_rf)

print("Random Forest Performance")
print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R2 Score:", rf_r2)

Random Forest Performance
MAE: 1.6746736735575465
RMSE: 2.19810794223221
R2 Score: 0.5437878198086097

 XGBoost Regressor

In [ ]:
xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=6,
    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
y_pred_xgb = xgb_model.predict(X_test)

In [ ]:
xgb_mae = mean_absolute_error(y_test, y_pred_xgb)

xgb_rmse = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

xgb_r2 = r2_score(y_test, y_pred_xgb)

print("XGBoost Performance")
print("MAE:", xgb_mae)
print("RMSE:", xgb_rmse)
print("R2 Score:", xgb_r2)

XGBoost Performance
MAE: 1.6871787578914996
RMSE: 2.1800625400959004
R2 Score: 0.5512476351718528

In [ ]:
xgb_results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred_xgb
})

xgb_results.head(10)

      Actual  Predicted
0  10.440887   8.671866
1   4.304065   3.506866
2  12.842705  11.457658
3   9.747360  10.943945
4  10.234588  10.801654
5  12.152867  10.829464
6   4.189655   7.918324
7  13.150762   9.930892
8  12.294825  11.078169
9   5.641907   3.474185

In [ ]:
comparison = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Random Forest",
        "XGBoost"],
    "MAE": [ lr_mae , rf_mae , xgb_mae],
    "RMSE": [ lr_rmse , rf_rmse, xgb_rmse],
    "R2 Score": [ lr_r2 , rf_r2 , xgb_r2 ]
})

comparison

               Model       MAE      RMSE  R2 Score
0  Linear Regression  1.811719  2.285854  0.506638
1      Random Forest  1.674674  2.198108  0.543788
2            XGBoost  1.687179  2.180063  0.551248

Three regression algorithms were evaluated for predicting book popularity.

Linear Regression served as a baseline model and achieved an R² score of 0.507. Ensemble tree-based methods produced stronger performance, indicating the presence of nonlinear relationships within the dataset.

Random Forest improved predictive accuracy, achieving an R² score of 0.544. XGBoost delivered the best overall performance with an R² score of 0.551 and the lowest RMSE value, making it the most effective model for predicting book popularity in this study.

Based on model evaluation results, XGBoost Regressor was selected as the final model for predicting book popularity.

In [ ]:
import joblib

joblib.dump(xgb_model, "xgboost_model.pkl")

['xgboost_model.pkl']

In [ ]:
joblib.dump(X.columns.tolist(), "feature_columns.pkl")

['feature_columns.pkl']



To support future deployment, the final model and preprocessing components are saved. These files will be reused in the Flask application to ensure that new user inputs are transformed consistently before prediction.